name: aptiquest
description: Aptiquest - Dungeon of Placements

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flame: ^1.10.0
  flame_audio: ^2.0.0
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.11
  firebase_auth: ^5.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/images/app_icon.png
  adaptive_icon_background: "#0B3FA7"
  adaptive_icon_foreground: assets/images/app_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/audio/bgm.mpeg
    - assets/images/app_icon.png
    - assets/images/player_sheet.png
    - assets/images/enemy_sheet.png
    - assets/images/slash.png