// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChQ6h-gKFB33g3ZLp1l4XYTeJPDkA20qE',
    appId: '1:324709087638:web:8f66adf6fc5aace07205b7',
    messagingSenderId: '324709087638',
    projectId: 'flutter-ai-playground-42e4e',
    authDomain: 'flutter-ai-playground-42e4e.firebaseapp.com',
    databaseURL: 'https://flutter-ai-playground-42e4e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-ai-playground-42e4e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6vST5dUoE2yfysXsKwUfWTVsZ5oGTgps',
    appId: '1:324709087638:android:0c813e9f44994d787205b7',
    messagingSenderId: '324709087638',
    projectId: 'flutter-ai-playground-42e4e',
    databaseURL: 'https://flutter-ai-playground-42e4e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-ai-playground-42e4e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChQ6h-gKFB33g3ZLp1l4XYTeJPDkA20qE',
    appId: '1:324709087638:web:f54e47143d3106f87205b7',
    messagingSenderId: '324709087638',
    projectId: 'flutter-ai-playground-42e4e',
    authDomain: 'flutter-ai-playground-42e4e.firebaseapp.com',
    databaseURL: 'https://flutter-ai-playground-42e4e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-ai-playground-42e4e.firebasestorage.app',
  );
}
